Make sure model names are PascalCase too
paljs/prisma-tools pull request #204
Opened 2021-05-03 07:48 UTC by mubaidr

By default this scripts ignore lowercase model names and but converts `relations`, `snake_case` naming to `PascalCase`. 

This edit ensures that all models are consistently named using `PascalCase`

**Example schema:**
```
model attachment {
  id               Int            @id @default(autoincrement())
  path             String
  attachment_type_id Int 
  attachment_type   attachment_type @relation(name: "attachment_to_attachment_type", fields: [attachment_type_id], references: [id])

  @@map("attachment")
}

model attachment_type {
  id          Int          @id @default(autoincrement())
  title       String?      @unique
  attachments attachment[] @relation(name: "attachment_to_attachment_type")
}
```

**Current conversion:** 
```
model attachment {
  id               Int            @id @default(autoincrement())
  path             String
  attachmentTypeId Int            @map("attachment_type_id")
  attachmentType   AttachmentType @relation(name: "attachmentToattachment_type", fields: [attachmentTypeId], references: [id])

  @@map("attachment")
}

model AttachmentType {
  id          Int          @id @default(autoincrement())
  title       String?      @unique
  attachments attachment[] @relation(name: "attachmentToattachment_type")

  @@map("attachment_type")
}
```

**new/Proposed changes:** 
```
model Attachment {
  id               Int            @id @default(autoincrement())
  path             String
  attachmentTypeId Int            @map("attachment_type_id")
  attachmentType   AttachmentType @relation(name: "attachmentToattachment_type", fields: [attachmentTypeId], references: [id])

  @@map("attachment")
}

model AttachmentType {
  id          Int          @id @default(autoincrement())
  title       String?      @unique
  attachments Attachment[] @relation(name: "attachmentToattachment_type")

  @@map("attachment_type")
}
```

2021-05-04 23:16 UTC, AhmedElywa requested changes

2021-05-04 23:16 UTC, AhmedElywa commented on packages/schema/src/camelCase.ts
>              if (cleanLine[1].includes('_') && kind !== 'enum') {
look here in the statement. It will not update the word if not include `_`, so I think you didn't test your code

2021-05-04 23:16 UTC, AhmedElywa commented on packages/schema/src/camelCase.ts
> -  private convertWord(word: string, model = false) {
and here you removed the arg that make me know If I work with the model name or the field and with current code, you will update all fields to start with upper char

2021-05-05 02:16 UTC, mubaidr commented
Yeah. It was just a quick dirty try to fix.

2021-05-05 02:16 UTC, closed without merging

2021-05-05 02:20 UTC, AhmedElywa commented
I will try to fix this issue in my next version