feature: prisma-select transform option suggestion
paljs/prisma-tools pull request #297
Opened 2023-05-10 09:54 UTC by CreeJee

## Background 
I need to select not only attributes like orderBy, for relational fields. 
And sometimes we need to add for optional select object "complex query prisma object".

## what changed
- add option for transform,
    - "find": search graphql field name callback
    - "update": when found search callback that change property
- update deps for latest
- fix some tests working on windows os 
- change dmmf snapshot 

Sorry for my bad English!

2023-05-10 16:19 UTC, AhmedElywa commented
It's a very big pull request give me some time to review this code

2023-05-10 16:25 UTC, AhmedElywa commented on packages/create/package.json
> +    "typescript": "^5.x",
```suggestion
    "typescript": "^5",
```

2023-05-10 16:25 UTC, AhmedElywa commented on packages/display/package.json
> +    "typescript": "^5.x",
```suggestion
    "typescript": "^5",
```

2023-05-10 16:25 UTC, AhmedElywa commented on packages/generator/package.json
> +    "typescript": "^5.x",
```suggestion
    "typescript": "^5",
```

2023-05-10 16:31 UTC, AhmedElywa requested changes

2023-05-10 16:31 UTC, AhmedElywa commented on packages/schema/package.json
> +    "typescript": "^5.x",
```suggestion
    "typescript": "^5",
```

2023-05-10 16:31 UTC, AhmedElywa commented on packages/utils/package.json
> +    "typescript": "^5.x",
```suggestion
    "typescript": "^5",
```

2023-05-23 01:11 UTC, CreeJee commented on packages/plugins/src/select.ts
> +  transform?: FindAndTransformOption[];
Okay 👍

2023-08-20 19:51 UTC, AhmedElywa commented
We have a big of changes in our project to support prisma v5 
if you want to merge this, please update it

2023-08-24 21:57 UTC, CreeJee commented
okay...
but i have a no time to merge suggestion...
but i'll try it

2023-08-25 21:01 UTC, closed without merging

2023-08-25 21:01 UTC, AhmedElywa commented
Thanks, i closed it for now